spin_manifest_version = 2

[application]
name = "crud-api"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "crud-api"

[component.crud-api]
source = "../../target/wasm32-wasip1/release/crud_api.wasm"
